package com.smartcampus.entity;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.smartcampus.enums.LoginStatus;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA entity representing a single login attempt, mapped to the {@code login_history} table.
 *
 * <p>Every call to {@code POST /auth/login} produces one row — whether the attempt
 * succeeds or fails. This gives users visibility into their recent login activity
 * and helps detect suspicious access from unexpected locations or devices.
 *
 * <p>Design decisions:
 * <ul>
 *   <li>{@code user_id} is nullable — a FAILED attempt with an unknown email has no
 *       associated user. The FK uses {@code ON DELETE SET NULL} so history is preserved
 *       even when a user account is hard-deleted.</li>
 *   <li>{@code email} is always stored so FAILED attempts with an unknown email are
 *       still searchable without a user reference.</li>
 *   <li>Rows are never deleted — this is a permanent security audit trail.</li>
 *   <li>The {@link User} association is LAZY and {@link JsonIgnore}-protected to prevent
 *       Hibernate proxy serialization errors when this entity is serialized directly.</li>
 * </ul>
 *
 * <p>Column names use snake_case to match the SQL schema in {@code V1__init_schema.sql}.
 *
 * @author  Smart Campus Team — IT3030 PAF 2026, SLIIT
 * @see     com.smartcampus.repository.LoginHistoryRepository
 * @see     com.smartcampus.service.LoginHistoryService
 */
@Entity
@Table(name = "login_history")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class LoginHistory {

    // ── Primary key ───────────────────────────────────────────────────────────

    /** Surrogate UUID primary key generated by the database via {@code gen_random_uuid()}. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    // ── Owning user (nullable) ─────────────────────────────────────────────────

    /**
     * The user who made this login attempt.
     *
     * <p>May be {@code null} for FAILED attempts where the submitted email does not
     * match any account (the user cannot be resolved). Loaded lazily — the user
     * object is not needed for the login-history list view.
     *
     * <p>{@link JsonIgnore} prevents Jackson from serialising the Hibernate LAZY proxy,
     * which would cause a {@code ByteBuddyInterceptor} serialization error.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = true)
    @JsonIgnore
    private User user;

    // ── Attempted email ───────────────────────────────────────────────────────

    /**
     * The email address submitted in the login request.
     * Always present — even for FAILED attempts where the email is unknown.
     */
    @Column(name = "email", nullable = false, length = 255)
    private String email;

    // ── Request metadata ──────────────────────────────────────────────────────

    /**
     * The IP address of the client making the login request.
     * Supports both IPv4 (max 15 chars) and IPv6 (max 45 chars).
     * May be {@code null} if the IP could not be determined.
     */
    @Column(name = "ip_address", length = 45)
    private String ipAddress;

    /**
     * The full User-Agent header from the login request.
     * Contains browser name, version, and OS information.
     * May be {@code null} if the header was absent.
     */
    @Column(name = "user_agent", length = 500)
    private String userAgent;

    // ── Outcome ───────────────────────────────────────────────────────────────

    /**
     * Whether the login attempt succeeded or failed.
     * Stored as a VARCHAR ({@code SUCCESS} / {@code FAILED}) to match the
     * {@code CHECK} constraint in the database schema.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 10)
    private LoginStatus status;

    // ── Audit timestamp ───────────────────────────────────────────────────────

    /**
     * UTC timestamp of when this login attempt was recorded.
     * Set automatically by Hibernate on insert; never modified.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
}
