package com.smartcampus.entity;

import com.smartcampus.enums.NotificationType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA entity representing a system notification delivered to a user,
 * mapped to the {@code notifications} table.
 *
 * <p>Notifications are generated by other modules (Booking, Ticket) via
 * {@link com.smartcampus.service.NotificationService#sendNotification} and are
 * never created directly. The notification lifecycle is:
 * <ol>
 *   <li>Another module calls {@code NotificationService.sendNotification()} —
 *       the service checks the user's preferences before persisting.</li>
 *   <li>The frontend polls or receives a WebSocket push and renders the notification
 *       in the bell-icon dropdown.</li>
 *   <li>The user opens the notification — the frontend calls
 *       {@code PATCH /notifications/{id}/read} to set {@code readAt}.</li>
 *   <li>The user deletes the notification — the row is hard-deleted
 *       (no soft-delete on this table by design).</li>
 * </ol>
 *
 * <p>Schema notes:
 * <ul>
 *   <li>No {@code title} column — the DB table only stores a {@code message} body.</li>
 *   <li>No {@code updated_at} column — notifications are immutable once created;
 *       only {@code read_at} is ever written after insert.</li>
 *   <li>{@code type} is constrained by a PostgreSQL {@code CHECK} to the values
 *       defined in {@link NotificationType}.</li>
 *   <li>{@code related_entity_type} accepts {@code 'BOOKING'} or {@code 'TICKET'} only,
 *       enforced by a database {@code CHECK} constraint.</li>
 * </ul>
 *
 * @author  Smart Campus Team — IT3030 PAF 2026, SLIIT
 * @see     NotificationType
 * @see     com.smartcampus.service.NotificationService
 */
@Entity
@Table(name = "notifications")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Notification {

    // ── Primary key ───────────────────────────────────────────────────────────

    /**
     * Surrogate UUID primary key generated by the database via
     * {@code gen_random_uuid()}, consistent with all other entity PKs.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    // ── Ownership ─────────────────────────────────────────────────────────────

    /**
     * The user to whom this notification is addressed.
     * Loaded lazily — the user record is rarely needed when processing
     * notification lists (the {@code user_id} FK value is sufficient for
     * most queries).
     *
     * <p>{@code ON DELETE CASCADE} in the schema ensures notifications are
     * automatically removed if the user account is hard-deleted.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    // ── Content ───────────────────────────────────────────────────────────────

    /**
     * Classification of this notification, determining the icon and colour
     * rendered by the frontend and which preference setting gates delivery.
     * Stored as the enum's string name (e.g. {@code "BOOKING_APPROVED"}) to
     * satisfy the database {@code CHECK} constraint.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, length = 60)
    private NotificationType type;

    /**
     * The human-readable notification body displayed to the user.
     * Generated by the originating module (Booking, Ticket) and should
     * be concise enough to render within a notification dropdown.
     */
    @Column(name = "message", nullable = false, columnDefinition = "TEXT")
    private String message;

    // ── Deep-link context ─────────────────────────────────────────────────────

    /**
     * The category of the entity this notification refers to.
     * Constrained by the database to {@code 'BOOKING'} or {@code 'TICKET'}, or
     * {@code null} for system announcements that don't link to a specific entity.
     *
     * <p>Used together with {@link #relatedEntityId} so the frontend can construct
     * a deep-link URL (e.g. {@code /bookings/abc-123}) when the user clicks the notification.
     */
    @Column(name = "related_entity_type", nullable = true, length = 20)
    private String relatedEntityType;

    /**
     * The UUID of the related booking or ticket that triggered this notification.
     * {@code null} for {@link NotificationType#SYSTEM_ANNOUNCEMENT} notifications
     * that do not reference a specific resource.
     */
    @Column(name = "related_entity_id", nullable = true)
    private UUID relatedEntityId;

    // ── Read state ────────────────────────────────────────────────────────────

    /**
     * UTC timestamp of when the user read this notification.
     * {@code null} indicates the notification is still <em>unread</em>.
     *
     * <p>Using a timestamp instead of a boolean {@code is_read} flag preserves
     * richer data (when it was read) and avoids a redundant two-column design.
     */
    @Column(name = "read_at", nullable = true)
    private LocalDateTime readAt;

    // ── Audit ─────────────────────────────────────────────────────────────────

    /**
     * UTC timestamp set automatically when the notification row is first inserted.
     * Notifications are immutable after creation — there is no {@code updated_at}
     * column on this table by design.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    // =========================================================================
    // Convenience methods
    // =========================================================================

    /**
     * Returns {@code true} if the user has read this notification.
     *
     * <p>A notification is considered read when {@link #readAt} has been set to a
     * non-null timestamp by a call to {@code NotificationService.markAsRead()}.
     *
     * @return {@code true} if {@code readAt} is non-null, {@code false} if unread
     */
    public boolean isRead() {
        return readAt != null;
    }
}
