package com.smartcampus.entity;

import com.smartcampus.enums.NotificationType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA entity representing a user's opt-in/opt-out preference for a specific
 * notification type, mapped to the {@code notification_preferences} table.
 *
 * <p>Design philosophy — <em>absence means enabled</em>:
 * <ul>
 *   <li>A row only exists when the user has explicitly changed the default.
 *       If no row is found for a given (user, type) pair, the system treats
 *       the preference as <strong>enabled</strong>.</li>
 *   <li>This means a brand-new user receives all notification types by default
 *       without needing rows pre-seeded for them.</li>
 *   <li>{@link com.smartcampus.service.NotificationService#isNotificationEnabled}
 *       encapsulates this defaulting logic — callers never check this table directly.</li>
 * </ul>
 *
 * <p>Schema notes:
 * <ul>
 *   <li>The DB column name is {@code type} (not {@code notification_type});
 *       the Java field is named {@code notificationType} for clarity and mapped
 *       via {@code @Column(name = "type")}.</li>
 *   <li>A {@code UNIQUE} constraint on {@code (user_id, type)} ensures at most
 *       one preference row per user per notification type.</li>
 *   <li>No {@code created_at} column — only {@code updated_at} is present,
 *       tracking when the preference was last changed.</li>
 * </ul>
 *
 * @author  Smart Campus Team — IT3030 PAF 2026, SLIIT
 * @see     NotificationType
 * @see     com.smartcampus.service.NotificationService
 */
@Entity
@Table(
    name = "notification_preferences",
    uniqueConstraints = @UniqueConstraint(
        name = "uq_notification_pref",
        columnNames = {"user_id", "type"}
    )
)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class NotificationPreference {

    // ── Primary key ───────────────────────────────────────────────────────────

    /**
     * Surrogate UUID primary key generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    // ── Ownership ─────────────────────────────────────────────────────────────

    /**
     * The user who owns this preference setting.
     * Loaded lazily — most preference queries only need the preference value,
     * not the full user graph.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    // ── Preference fields ─────────────────────────────────────────────────────

    /**
     * The notification type this preference applies to.
     * Stored as the enum's string name to match the PostgreSQL {@code CHECK} constraint.
     *
     * <p>Note: the database column is named {@code type} — the Java field uses the
     * more descriptive name {@code notificationType} to avoid clashing with Java's
     * reserved word and to clarify the field's purpose in the context of this entity.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "type", nullable = false, length = 60)
    private NotificationType notificationType;

    /**
     * Whether the user wants to receive this type of notification.
     * {@code true} = receive (default), {@code false} = suppressed.
     *
     * <p>Remember: when <em>no row exists</em> for a (user, type) pair,
     * the effective value is also {@code true} (enabled by default).
     */
    @Column(name = "enabled", nullable = false)
    @Builder.Default
    private boolean enabled = true;

    // ── Audit ─────────────────────────────────────────────────────────────────

    /**
     * Automatically updated by Hibernate on every {@code UPDATE} to track when
     * the preference was last changed by the user.
     */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;
}
