package com.smartcampus.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA entity representing a persisted refresh token, mapped to the {@code refresh_tokens} table.
 *
 * <p>The dual-token pattern used in this system works as follows:
 * <ol>
 *   <li>The server issues a short-lived <b>access token</b> (15 min) and a long-lived
 *       <b>refresh token</b> (7 days) on every login or registration.</li>
 *   <li>When the access token expires, the client sends the refresh token to
 *       {@code POST /auth/refresh} to receive a new pair of tokens (token rotation).</li>
 *   <li>On logout, the refresh token's {@code revoked} flag is set to {@code true},
 *       invalidating it immediately even if it has not yet expired.</li>
 * </ol>
 *
 * <p>Design decisions:
 * <ul>
 *   <li>{@code token} stores the raw JWT refresh token string (already a signed,
 *       opaque value). The unique constraint on the column prevents token reuse.</li>
 *   <li>Token rotation is enforced: each refresh call revokes the incoming token
 *       and issues a new one, limiting the blast radius if a token is stolen.</li>
 *   <li>The {@code ON DELETE CASCADE} FK means tokens are automatically removed
 *       when the owning user account is hard-deleted.</li>
 *   <li>A scheduled job should periodically delete rows where
 *       {@code expires_at < NOW()} to prevent unbounded table growth
 *       (supported by {@link com.smartcampus.repository.RefreshTokenRepository#deleteAllByExpiresAtBefore}).</li>
 * </ul>
 *
 * <p>Column names use snake_case to match the SQL schema in {@code V1__init_schema.sql}.
 * Flyway owns the DDL, so the entity must not diverge from the migration.
 *
 * @author  Smart Campus Team — IT3030 PAF 2026, SLIIT
 * @see     com.smartcampus.repository.RefreshTokenRepository
 * @see     com.smartcampus.service.AuthService
 */
@Entity
@Table(name = "refresh_tokens")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RefreshToken {

    // ── Primary key ───────────────────────────────────────────────────────────

    /**
     * Surrogate UUID primary key generated by the database via
     * {@code gen_random_uuid()}, consistent with the {@code users} table strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    // ── Token value ───────────────────────────────────────────────────────────

    /**
     * The JWT refresh token string issued to the client.
     * Stored as-is — the JWT is already a signed, tamper-evident value.
     * The {@code UNIQUE} constraint on this column prevents the same token
     * string from appearing in multiple rows (defence against re-insertion attacks).
     */
    @Column(name = "token", nullable = false, unique = true, length = 500)
    private String token;

    // ── Owning user ───────────────────────────────────────────────────────────

    /**
     * The user to whom this refresh token belongs.
     *
     * <p>Loaded lazily to avoid joining the {@code users} table on every token
     * lookup when only the token validity (revoked / expired) needs to be checked.
     * The {@code ON DELETE CASCADE} FK in the schema means this row is automatically
     * removed if the user is hard-deleted.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    // ── Validity fields ───────────────────────────────────────────────────────

    /**
     * Absolute expiry timestamp of this token (7 days from issuance).
     * After this time the token must be rejected even if {@code revoked} is {@code false}.
     */
    @Column(name = "expires_at", nullable = false)
    private LocalDateTime expiresAt;

    /**
     * Whether this token has been explicitly invalidated.
     *
     * <p>Set to {@code true} when the user logs out or when token rotation occurs
     * (a new token is issued at {@code POST /auth/refresh}, and the consumed token
     * is revoked to prevent replay attacks).
     */
    @Column(name = "revoked", nullable = false)
    @Builder.Default
    private boolean revoked = false;

    // ── Audit timestamp ───────────────────────────────────────────────────────

    /**
     * UTC timestamp of when this token was created. Set automatically by Hibernate
     * on insert and never modified. Useful for audit and analytics queries.
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    // =========================================================================
    // Convenience methods
    // =========================================================================

    /**
     * Returns {@code true} if this token is currently usable — i.e. it has
     * not been revoked AND it has not yet passed its expiry timestamp.
     *
     * @return {@code true} if the token is valid, {@code false} otherwise
     */
    public boolean isValid() {
        return !revoked && expiresAt.isAfter(LocalDateTime.now());
    }
}
