package com.smartcampus.entity;

import com.smartcampus.enums.UserRole;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

import java.time.LocalDateTime;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

/**
 * JPA entity representing a system user, mapped to the {@code users} table.
 *
 * <p>This class serves a dual purpose:
 * <ol>
 *   <li><b>JPA entity</b> — persists user data to PostgreSQL via Hibernate.</li>
 *   <li><b>Spring Security principal</b> — implements {@link UserDetails} so the
 *       object returned by {@code UserDetailsService} can be used directly by
 *       the security filter chain without an adapter layer.</li>
 * </ol>
 *
 * <p>Design notes:
 * <ul>
 *   <li>{@code passwordHash} is nullable to support OAuth-only accounts that
 *       never set a local password.</li>
 *   <li>Soft delete via {@code deletedAt}: a non-null value means the user has
 *       been logically removed. Hard deletes are never performed to preserve
 *       referential integrity with bookings, tickets, and comments.</li>
 *   <li>Optimistic locking is intentionally omitted here — the {@code bookings}
 *       and {@code tickets} tables carry their own {@code version} columns for
 *       the race-condition-prone workflows.</li>
 * </ul>
 *
 * <p>Column names use snake_case to match the SQL schema exactly.
 * Flyway owns all DDL, so {@code ddl-auto=validate} will reject any mismatch.
 *
 * @author  Smart Campus Team — IT3030 PAF 2026, SLIIT
 * @see     UserRole
 * @see     org.springframework.security.core.userdetails.UserDetails
 */
@Entity
@Table(name = "users")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class User implements UserDetails {

    // ── Primary Key ───────────────────────────────────────────────────────────

    /**
     * Surrogate primary key. UUID is generated by the database via
     * {@code gen_random_uuid()} (PostgreSQL built-in), so the strategy is
     * {@link GenerationType#UUID} which delegates to the DB function.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    // ── Core identity fields ──────────────────────────────────────────────────

    /** Full display name of the user (max 100 chars, matches schema VARCHAR(100)). */
    @Column(name = "name", nullable = false, length = 100)
    private String name;

    /**
     * Unique email address used for authentication.
     * The database enforces uniqueness via {@code CONSTRAINT uq_users_email}.
     */
    @Column(name = "email", nullable = false, unique = true, length = 255)
    private String email;

    /**
     * BCrypt-hashed password. Nullable because OAuth-only users never set a
     * local password — they authenticate exclusively via their OAuth provider.
     */
    @Column(name = "password_hash", nullable = true, length = 255)
    private String passwordHash;

    // ── Role ──────────────────────────────────────────────────────────────────

    /**
     * Access-control role. Persisted as the enum's string name (e.g. "ADMIN")
     * to match the {@code CHECK} constraint in the SQL schema.
     *
     * @see UserRole
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "role", nullable = false, length = 20)
    @Builder.Default
    private UserRole role = UserRole.USER;

    // ── Profile ───────────────────────────────────────────────────────────────

    /**
     * URL to the user's profile picture (Cloudinary / OAuth provider avatar).
     * Nullable — users are not required to have a profile picture.
     */
    @Column(name = "profile_picture", nullable = true, length = 500)
    private String profilePicture;

    // ── Account state ─────────────────────────────────────────────────────────

    /**
     * When {@code false}, the account has been administratively disabled.
     * The user can no longer authenticate, but their data is preserved.
     * Maps to Spring Security's {@link UserDetails#isEnabled()}.
     */
    @Column(name = "is_active", nullable = false)
    @Builder.Default
    private Boolean isActive = Boolean.TRUE;

    /**
     * Soft-delete timestamp. {@code null} means the account is active.
     * A non-null value means the account has been logically deleted.
     * Queries should filter with {@code WHERE deleted_at IS NULL} to
     * exclude soft-deleted users.
     */
    @Column(name = "deleted_at", nullable = true)
    private LocalDateTime deletedAt;

    // ── Audit timestamps ──────────────────────────────────────────────────────

    /**
     * Automatically set to the current UTC timestamp when the row is first
     * inserted. Never updated after that ({@code updatable = false}).
     */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Automatically updated to the current UTC timestamp on every
     * {@code UPDATE} operation by Hibernate.
     */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    // =========================================================================
    // UserDetails implementation
    // Spring Security calls these methods during authentication and authorisation.
    // =========================================================================

    /**
     * Returns the single granted authority derived from this user's role.
     *
     * <p>Spring Security's {@code hasRole("ADMIN")} expression internally
     * prepends "ROLE_" and matches against this collection, so returning
     * {@code "ROLE_ADMIN"} from {@link UserRole#getAuthority()} is correct.
     *
     * @return an immutable singleton list containing the role authority
     */
    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        // Wrap the role's authority string in a SimpleGrantedAuthority so Spring
        // Security can compare it against security expressions like hasRole("ADMIN").
        return List.of(new SimpleGrantedAuthority(role.getAuthority()));
    }

    /**
     * Returns the hashed password used for local (email + password) authentication.
     *
     * <p>Spring Security compares this value (via {@link org.springframework.security.crypto.password.PasswordEncoder})
     * against the raw password supplied during login. OAuth users will have
     * {@code null} here — they are never challenged for a password.
     *
     * @return BCrypt password hash, or {@code null} for OAuth-only accounts
     */
    @Override
    public String getPassword() {
        return passwordHash;
    }

    /**
     * Returns the username used for authentication — in this system, the email
     * address serves as the unique username.
     *
     * @return the user's email address
     */
    @Override
    public String getUsername() {
        return email;
    }

    /**
     * Indicates whether the account has expired. This system does not implement
     * account expiry, so always returns {@code true} (non-expired).
     *
     * @return {@code true} always
     */
    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    /**
     * Indicates whether the account is locked. This system does not implement
     * account locking (only soft-delete and is_active), so always returns
     * {@code true} (non-locked).
     *
     * @return {@code true} always
     */
    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    /**
     * Indicates whether the user's credentials have expired. This system does
     * not implement credential expiry, so always returns {@code true}.
     *
     * @return {@code true} always
     */
    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    /**
     * Indicates whether the account is enabled and allowed to authenticate.
     * Maps directly to the {@code is_active} column. Admins can disable accounts
     * by setting this to {@code false} without deleting the user's data.
     *
     * @return {@code true} if the account is active, {@code false} if disabled
     */
    @Override
    public boolean isEnabled() {
        // Guard against null — DB default is TRUE but the field could be null
        // if an entity is constructed programmatically without the @Builder.Default.
        return Boolean.TRUE.equals(isActive);
    }
}
